name: MSBuild

on:
  push:
    branches:
      - "master"

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: |
        msbuild /m /p:Configuration=Release /p:platform=x64 ${{env.SOLUTION_FILE_PATH}}
        msbuild /m /p:Configuration=Release /p:platform=x86 ${{env.SOLUTION_FILE_PATH}}
        msbuild /m /p:Configuration=NOVCLTL /p:platform=x64 ${{env.SOLUTION_FILE_PATH}}
        msbuild /m /p:Configuration=NOVCLTL /p:platform=x86 ${{env.SOLUTION_FILE_PATH}}
        md fe
        md fe\x64
        move x64\Release\fe.exe fe\x64\fe.exe
        copy example.json fe\x64\fe.json
        md fe\x86
        move Win32\Release\fe.exe fe\x86\fe.exe
        copy example.json fe\x86\fe.json
        md fe\NOVCLTLx64
        move x64\NOVCLTL\fe.exe fe\NOVCLTLx64\fe.exe
        copy example.json fe\NOVCLTLx64\fe.json
        md fe\NOVCLTLx86
        move Win32\NOVCLTL\fe.exe fe\NOVCLTLx86\fe.exe
        copy example.json fe\NOVCLTLx86\fe.json
        copy LICENSE fe\LICENSE
        copy README.md fe\README.md

    - name: Run UPX
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        files: |
          .\fe\NOVCLTLx64\fe.exe
          .\fe\NOVCLTLx86\fe.exe
        args: -fq

    - uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: 'fe.zip'
        directory: '.'
        path: 'fe'

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Development Build"
        files: |
          fe.zip
